plugin: aws_ec2

regions:
  - ap-northeast-2

filters:
  instance-state-name: running

groups:
  ssm: "'SSM' in tags.Environment"

hostnames:
  - tag:Name
  - private-ip-address

compose:
  ansible_host: instance_id